# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsget < Formula
  desc "wsget binary"
  homepage "https://gihub.com/ksysoev/wsget"
  version "0.4.2"

  on_macos do
    on_intel do
      url "https://github.com/ksysoev/wsget/releases/download/v0.4.2/wsget_Darwin_x86_64.tar.gz"
      sha256 "36e8c2810fe3bdabbc29a88b7a40e40a3a9193d8db66a490d7a1480b96cb8b10"

      def install
        bin.install 'wsget'
      end
    end
    on_arm do
      url "https://github.com/ksysoev/wsget/releases/download/v0.4.2/wsget_Darwin_arm64.tar.gz"
      sha256 "dc56d5edab3043beef3f66e0a7f2449cc8c803a966c74eaf9996f8f86b6cedb1"

      def install
        bin.install 'wsget'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ksysoev/wsget/releases/download/v0.4.2/wsget_Linux_x86_64.tar.gz"
        sha256 "576904cb1af125834f9752cce9eb0a30140c95d59e721547bf489792d0c1d243"

        def install
          bin.install 'wsget'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ksysoev/wsget/releases/download/v0.4.2/wsget_Linux_arm64.tar.gz"
        sha256 "1b88f036ee88f3fd57ae213cc481cd535bf6d08667e1037a24b2c5ebdcd03e5d"

        def install
          bin.install 'wsget'
        end
      end
    end
  end

  test do
    system "#{bin}/wsget"
  end
end
