# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsget < Formula
  desc "wsget binary"
  homepage "https://gihub.com/ksysoev/wsget"
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/ksysoev/wsget/releases/download/v0.5.0/wsget_Darwin_x86_64.tar.gz"
      sha256 "cfcc587610a4ee02aaf76435bd80c8cf7eaa55500b027575f609f1866b37b1d9"

      def install
        bin.install 'wsget'
      end
    end
    on_arm do
      url "https://github.com/ksysoev/wsget/releases/download/v0.5.0/wsget_Darwin_arm64.tar.gz"
      sha256 "bc1266cb6138cdb48d753d7322e3abf0c8ed07dfb4810837ba090dc0e2120d4c"

      def install
        bin.install 'wsget'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ksysoev/wsget/releases/download/v0.5.0/wsget_Linux_x86_64.tar.gz"
        sha256 "92c828312c298e150e27e6191dda9454d11c2052b60b797a6c824af3ed3ed896"

        def install
          bin.install 'wsget'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ksysoev/wsget/releases/download/v0.5.0/wsget_Linux_arm64.tar.gz"
        sha256 "e2bcef76120bbebe5ee0d84734866c01abe82107f975ab2c16cc3ac7d2abe80d"

        def install
          bin.install 'wsget'
        end
      end
    end
  end

  test do
    system "#{bin}/wsget"
  end
end
