# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsget < Formula
  desc "wsget binary"
  homepage "https://gihub.com/ksysoev/wsget"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ksysoev/wsget/releases/download/v0.4.1/wsget_Darwin_x86_64.tar.gz"
      sha256 "808ca567be022abc9a75ee9e09e15474196bb92e66577f295a712f80fe5c2039"

      def install
        bin.install 'wsget'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ksysoev/wsget/releases/download/v0.4.1/wsget_Darwin_arm64.tar.gz"
      sha256 "17519f6da1f70479c4a26a37d4e8b977558f9a46dbe94f5376cfaf4e21332112"

      def install
        bin.install 'wsget'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ksysoev/wsget/releases/download/v0.4.1/wsget_Linux_x86_64.tar.gz"
      sha256 "f1cc2c9c868ccb0a9f881f084b6b827489f7b99b2c1ee87afbd9f7cf98d03503"

      def install
        bin.install 'wsget'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/wsget/releases/download/v0.4.1/wsget_Linux_arm64.tar.gz"
      sha256 "653669182bca3a63a5493c179d0ba1232f1563459de86c5b0501b5f699b3b69c"

      def install
        bin.install 'wsget'
      end
    end
  end

  test do
    system "#{bin}/wsget"
  end
end
